import { useState, useEffect, useRef } from 'react';
import { supabase } from '../../lib/supabase';
import { getAIQuota } from '../../lib/aiQuota';
import { Bot, Save, Wand2, FileText, Hash, Layout, AlignLeft, ChevronRight, AlertCircle, Sparkles } from 'lucide-react';

interface ScriptingStageProps {
  workflowId: string;
  contentType: string;
  onComplete: () => void;
  onSkip: () => void;
}

export function ScriptingStage({ workflowId, contentType, onComplete, onSkip }: ScriptingStageProps) {
  const [mode, setMode] = useState<'simple' | 'structured'>(
    ['video', 'blog'].includes(contentType) ? 'structured' : 'simple'
  );
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [aiError, setAiError] = useState<string | null>(null);
  const [script, setScript] = useState({ hook: '', body: '', cta: '', caption: '', hashtags: '' });
  const [notes, setNotes] = useState('');
  const [ideaTopic, setIdeaTopic] = useState('');
  const autoGeneratedRef = useRef(false);

  useEffect(() => {
    loadWorkflowData();
  }, [workflowId]);

  const loadWorkflowData = async () => {
    setLoading(true);
    const { data } = await supabase
      .from('content_workflow_stages')
      .select('script_content, idea_content')
      .eq('id', workflowId)
      .maybeSingle();

    let hasExistingScript = false;
    let topic = '';

    if (data) {
      if (data.idea_content) {
        topic = data.idea_content;
        setIdeaTopic(data.idea_content);
      }
      if (data.script_content) {
        hasExistingScript = true;
        const content = data.script_content as any;
        setScript({
          hook: content.hook || '',
          body: content.body || '',
          cta: content.cta || '',
          caption: content.caption || '',
          hashtags: Array.isArray(content.hashtags)
            ? content.hashtags.join(' ')
            : (content.hashtags || '')
        });
        setNotes(content.notes || '');
        if (content.notes && !content.hook) { setMode('simple'); }
      }
    }
    setLoading(false);

    // Auto-generate if we have a topic but no saved script yet
    if (topic && !hasExistingScript && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      generateScript(topic);
    }
  };

  const generateScript = async (topicOverride?: string) => {
    const topic = topicOverride || ideaTopic;
    if (!topic) return;
    setGenerating(true);
    setAiError(null);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const quota = await getAIQuota(user.id);
      if (quota && quota.requests_remaining <= 0) {
        throw new Error('Daily AI quota exceeded. Resets at midnight.');
      }

      const { data: fnData, error: fnError } = await supabase.functions.invoke('generate-script', {
        body: { userId: user.id, workflowId, topic, contentType, mode },
      });

      if (fnError) throw fnError;
      if (!fnData?.success) throw new Error(fnData?.error || 'Generation failed');

      const result = fnData.result;
      if (result.mode === 'simple' && result.notes) {
        setNotes(result.notes);
      } else if (result.mode === 'structured' && result.script) {
        setScript({
          hook: result.script.hook || '',
          body: result.script.body || '',
          cta: result.script.cta || '',
          caption: result.script.caption || '',
          hashtags: Array.isArray(result.script.hashtags)
            ? result.script.hashtags.join(' ')
            : (result.script.hashtags || ''),
        });
      }
    } catch (err: any) {
      console.error('generate-script error:', err);
      setAiError(err.message || 'AI generation failed. Try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async (completeStage = false) => {
    setLoading(true);
    const updateData: any = {
      script_content: {
        ...script,
        notes,
        hashtags: script.hashtags.split(' ').filter((tag: string) => tag.startsWith('#'))
      },
      updated_at: new Date().toISOString()
    };
    if (completeStage) {
      updateData.current_stage = 'creation';
      updateData.script_completed_at = new Date().toISOString();
    }
    await supabase.from('content_workflow_stages').update(updateData).eq('id', workflowId);
    if (completeStage) { onComplete(); }
    setLoading(false);
  };

  return (
    <div className="max-w-5xl mx-auto">
      {ideaTopic && (
        <div className="mb-6 p-4 bg-primary/10 border border-primary/20 rounded-xl">
          <p className="text-sm font-medium text-muted-foreground mb-1">Selected Idea:</p>
          <p className="text-lg font-bold text-foreground">{ideaTopic}</p>
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <h2 className="text-2xl font-bold text-foreground">Scripting</h2>
        <div className="flex bg-accent p-1 rounded-xl">
          <button
            onClick={() => setMode('simple')}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${
              mode === 'simple'
                ? 'bg-background shadow text-foreground'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            <AlignLeft className="w-4 h-4" /> Quick Notes
          </button>
          <button
            onClick={() => setMode('structured')}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${
              mode === 'structured'
                ? 'bg-background shadow text-foreground'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            <Layout className="w-4 h-4" /> Structured
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">

          {/* Generate button — prominent, always visible */}
          <button
            onClick={() => generateScript()}
            disabled={generating || !ideaTopic}
            className="w-full py-3 px-4 bg-primary/10 hover:bg-primary/20 border border-primary/25 hover:border-primary/40 text-primary font-semibold rounded-xl transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {generating ? (
              <><Wand2 className="w-4 h-4 animate-spin" /> Generating...</>
            ) : (
              <><Sparkles className="w-4 h-4" /> {mode === 'simple' ? 'Generate Outline' : 'Auto-Draft Script'}</>
            )}
          </button>

          {generating && (
            <p className="text-xs text-center text-muted-foreground animate-pulse">
              AI is writing your script based on the idea...
            </p>
          )}

          {aiError && (
            <div className="flex items-start gap-2 p-3 bg-destructive/10 border border-destructive/20 rounded-xl text-sm text-destructive">
              <AlertCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
              {aiError}
            </div>
          )}

          {mode === 'simple' ? (
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Jot down your concept, bullet points, or rough ideas here..."
              className="w-full p-6 rounded-2xl border border-border focus:ring-2 focus:ring-primary outline-none min-h-[400px] text-lg leading-relaxed bg-background text-foreground shadow-sm placeholder:text-muted-foreground resize-none"
            />
          ) : (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-semibold text-foreground mb-1">Visual Hook (0–3s)</label>
                <textarea
                  value={script.hook}
                  onChange={(e) => setScript({ ...script, hook: e.target.value })}
                  placeholder="The 'Stop the Scroll' moment..."
                  className="w-full p-4 rounded-xl border border-border focus:ring-2 focus:ring-primary outline-none min-h-[80px] bg-background text-foreground placeholder:text-muted-foreground"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-foreground mb-1">Body</label>
                <textarea
                  value={script.body}
                  onChange={(e) => setScript({ ...script, body: e.target.value })}
                  placeholder="The core value or story..."
                  className="w-full p-4 rounded-xl border border-border focus:ring-2 focus:ring-primary outline-none min-h-[200px] bg-background text-foreground placeholder:text-muted-foreground"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-foreground mb-1">CTA</label>
                <input
                  type="text"
                  value={script.cta}
                  onChange={(e) => setScript({ ...script, cta: e.target.value })}
                  placeholder="What should they do next?"
                  className="w-full p-4 rounded-xl border border-border focus:ring-2 focus:ring-primary outline-none bg-background text-foreground placeholder:text-muted-foreground"
                />
              </div>
            </div>
          )}
        </div>

        <div className="space-y-6">
          <div className="bg-card border border-border p-6 rounded-2xl h-full">
            <h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-muted-foreground" />
              Caption & Tags
            </h3>
            <div className="space-y-4">
              <textarea
                value={script.caption}
                onChange={(e) => setScript({ ...script, caption: e.target.value })}
                placeholder="Write your caption here (optional)..."
                className="w-full p-4 rounded-xl border border-border focus:ring-2 focus:ring-primary outline-none min-h-[200px] bg-background text-foreground placeholder:text-muted-foreground"
              />
              <div className="flex items-center gap-2 bg-background p-3 rounded-xl border border-border">
                <Hash className="w-4 h-4 text-muted-foreground" />
                <input
                  type="text"
                  value={script.hashtags}
                  onChange={(e) => setScript({ ...script, hashtags: e.target.value })}
                  placeholder="Add tags..."
                  className="flex-1 outline-none bg-transparent text-primary placeholder:text-muted-foreground"
                />
              </div>
            </div>
            <div className="mt-8 pt-6 border-t border-border space-y-3">
              <button
                onClick={() => handleSave(true)}
                disabled={loading}
                className="w-full py-3 px-4 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold rounded-xl transition-colors flex items-center justify-center gap-2 shadow-lg"
              >
                Save & Continue <ChevronRight className="w-4 h-4" />
              </button>
              <button
                onClick={onSkip}
                className="w-full py-2 text-muted-foreground hover:text-foreground text-sm font-medium transition-colors"
              >
                Skip Scripting
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
