import { useState, useEffect, useRef } from 'react';
import { supabase } from '../../lib/supabase';
import { getAIQuota } from '../../lib/aiQuota';
import { useAccount } from '../../contexts/AccountContext';
import { useBrand } from '../../contexts/BrandContext';
import { FileText, Hash, Layout, AlignLeft, ChevronRight, AlertCircle, Sparkles, Check } from 'lucide-react';

interface ScriptingStageProps {
  workflowId: string;
  contentType: string;
  onComplete: () => void;
  onSkip: () => void;
}

export function ScriptingStage({ workflowId, contentType, onComplete, onSkip }: ScriptingStageProps) {
  const { activeAccount } = useAccount();
  const { activeBrand } = useBrand();
  const [mode, setMode] = useState<'simple' | 'structured'>(
    ['video', 'blog'].includes(contentType) ? 'structured' : 'simple'
  );
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [aiError, setAiError] = useState<string | null>(null);
  const [script, setScript] = useState({ hook: '', body: '', cta: '', caption: '', hashtags: '' });
  const [notes, setNotes] = useState('');
  const [ideaTopic, setIdeaTopic] = useState('');
  const [hasVoice, setHasVoice] = useState(false);
  const autoGeneratedRef = useRef(false);

  useEffect(() => {
    loadWorkflowData();
  }, [workflowId]);

  // Whether the creator has built a Voice — drives the "in your voice" badge.
  useEffect(() => {
    (async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      if (!activeBrand) return;
      // Check the active account's voice first, then the user-level ("main")
      // row — mirroring the server-side fallback in _shared/voice.ts. The
      // account dimension must be pinned explicitly: with per-account rows in
      // the table an unfiltered .maybeSingle() would error on >1 rows.
      const hasUsableVoice = async (accountId: string | null) => {
        let q = supabase
          .from('user_content_profiles')
          .select('voice_profile, raw_analysis')
          .eq('user_id', user.id)
          .eq('brand_id', activeBrand.id);
        q = accountId ? q.eq('social_account_id', accountId) : q.is('social_account_id', null);
        const { data } = await q.maybeSingle();
        const v = data as { voice_profile?: unknown; raw_analysis?: { voice_signature?: string } } | null;
        return !!(v?.voice_profile || v?.raw_analysis?.voice_signature);
      };
      const active = activeAccount ? await hasUsableVoice(activeAccount.id) : false;
      setHasVoice(active || await hasUsableVoice(null));
    })();
  }, [activeAccount?.id, activeBrand]);

  const loadWorkflowData = async () => {
    setLoading(true);
    const { data } = await supabase
      .from('content_workflow_stages')
      .select('script_content, idea_content')
      .eq('id', workflowId)
      .maybeSingle();

    let hasExistingScript = false;
    let topic = '';

    if (data) {
      if (data.idea_content) {
        topic = data.idea_content;
        setIdeaTopic(data.idea_content);
      }
      if (data.script_content) {
        hasExistingScript = true;
        const content = data.script_content as any;
        setScript({
          hook: content.hook || '',
          body: content.body || '',
          cta: content.cta || '',
          caption: content.caption || '',
          hashtags: Array.isArray(content.hashtags)
            ? content.hashtags.join(' ')
            : (content.hashtags || '')
        });
        setNotes(content.notes || '');
        if (content.notes && !content.hook) { setMode('simple'); }
      }
    }
    setLoading(false);

    // Auto-generate if we have a topic but no saved script yet
    if (topic && !hasExistingScript && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      generateScript(topic);
    }
  };

  const generateScript = async (topicOverride?: string) => {
    const topic = topicOverride || ideaTopic;
    if (!topic) return;
    setGenerating(true);
    setAiError(null);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const quota = await getAIQuota(user.id);
      if (quota && quota.requestsRemaining <= 0) {
        throw new Error('Daily AI quota exceeded. Resets at midnight.');
      }

      const { data: fnData, error: fnError } = await supabase.functions.invoke('generate-script', {
        body: {
          userId: user.id,
          workflowId,
          topic,
          contentType,
          mode,
          // Account Switcher scope: script comes out in this account's voice
          // and niche (main-voice fallback server-side).
          ...(activeAccount ? { socialAccountId: activeAccount.id } : {}),
        },
      });

      if (fnError) throw fnError;
      if (!fnData?.success) throw new Error(fnData?.error || 'Generation failed');

      const result = fnData.result;
      if (result.mode === 'simple' && result.notes) {
        setNotes(result.notes);
      } else if (result.mode === 'structured' && result.script) {
        setScript({
          hook: result.script.hook || '',
          body: result.script.body || '',
          cta: result.script.cta || '',
          caption: result.script.caption || '',
          hashtags: Array.isArray(result.script.hashtags)
            ? result.script.hashtags.join(' ')
            : (result.script.hashtags || ''),
        });
      }
    } catch (err: any) {
      console.error('generate-script error:', err);
      setAiError(err.message || 'AI generation failed. Try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async (completeStage = false) => {
    setLoading(true);
    setAiError(null);
    const updateData: any = {
      script_content: {
        ...script,
        notes,
        hashtags: script.hashtags.split(' ').filter((tag: string) => tag.startsWith('#'))
      },
      updated_at: new Date().toISOString()
    };
    if (completeStage) {
      updateData.current_stage = 'creation';
      updateData.script_completed_at = new Date().toISOString();
    }
    try {
      const { error } = await supabase
        .from('content_workflow_stages')
        .update(updateData)
        .eq('id', workflowId);
      // Only advance the workflow if the save actually persisted — otherwise the
      // script is lost and the user is moved on thinking it was saved.
      if (error) throw error;
      if (completeStage) onComplete();
    } catch (err) {
      setAiError('Could not save your script. Check your connection and try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto">
      {ideaTopic && (
        <div className="mb-6 p-4 bg-card border border-border">
          <p className="t-micro mb-1">Selected idea</p>
          <p className="text-foreground" style={{ fontSize: '1.05rem', fontWeight: 500 }}>{ideaTopic}</p>
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <h2 className="text-foreground" style={{ fontSize: '1.5rem', fontWeight: 500, letterSpacing: '-0.01em', lineHeight: 1.15 }}>
          Scripting
        </h2>
        <div className="flex gap-2">
          <button
            onClick={() => setMode('simple')}
            className="t-micro px-3 py-2 border transition-colors flex items-center gap-2"
            style={{
              borderColor: mode === 'simple' ? 'var(--accent)' : 'var(--border)',
              color: mode === 'simple' ? 'var(--accent)' : 'var(--foreground)',
            }}
          >
            <AlignLeft className="w-3.5 h-3.5" /> Quick notes
          </button>
          <button
            onClick={() => setMode('structured')}
            className="t-micro px-3 py-2 border transition-colors flex items-center gap-2"
            style={{
              borderColor: mode === 'structured' ? 'var(--accent)' : 'var(--border)',
              color: mode === 'structured' ? 'var(--accent)' : 'var(--foreground)',
            }}
          >
            <Layout className="w-3.5 h-3.5" /> Structured
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">

          {/* Generate button — prominent, always visible */}
          <button
            onClick={() => generateScript()}
            disabled={generating || !ideaTopic}
            className="btn-ie w-full disabled:opacity-40 disabled:cursor-not-allowed"
          >
            <span className="btn-ie-text flex items-center gap-2">
              {generating
                ? <><span className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" /> Generating…</>
                : <><Sparkles className="w-4 h-4" /> {mode === 'simple' ? 'Generate outline' : 'Auto-draft script'}</>}
            </span>
          </button>

          {hasVoice && (
            <p className="t-micro text-center flex items-center justify-center gap-1" style={{ color: 'var(--accent)' }}>
              <Check className="w-3 h-3" /> Written in your voice
            </p>
          )}

          {generating && (
            <p className="t-body text-center animate-pulse">
              Writing your script based on the idea…
            </p>
          )}

          {aiError && (
            <div className="flex items-start gap-2 p-3 border border-border text-sm" style={{ color: '#B07050' }}>
              <AlertCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
              {aiError}
            </div>
          )}

          {mode === 'simple' ? (
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Jot down your concept, bullet points, or rough ideas here…"
              className="w-full p-6 border border-border bg-background text-foreground outline-none transition-colors focus:border-foreground min-h-[400px] text-lg leading-relaxed placeholder:text-muted-foreground resize-none"
            />
          ) : (
            <div className="space-y-4">
              <div>
                <label className="t-micro text-foreground block mb-1">Visual hook (0–3s)</label>
                <textarea
                  value={script.hook}
                  onChange={(e) => setScript({ ...script, hook: e.target.value })}
                  placeholder="The stop-the-scroll moment…"
                  className="w-full p-4 border border-border bg-background text-foreground outline-none transition-colors focus:border-foreground min-h-[80px] placeholder:text-muted-foreground"
                />
              </div>
              <div>
                <label className="t-micro text-foreground block mb-1">Body</label>
                <textarea
                  value={script.body}
                  onChange={(e) => setScript({ ...script, body: e.target.value })}
                  placeholder="The core value or story…"
                  className="w-full p-4 border border-border bg-background text-foreground outline-none transition-colors focus:border-foreground min-h-[200px] placeholder:text-muted-foreground"
                />
              </div>
              <div>
                <label className="t-micro text-foreground block mb-1">CTA</label>
                <input
                  type="text"
                  value={script.cta}
                  onChange={(e) => setScript({ ...script, cta: e.target.value })}
                  placeholder="What should they do next?"
                  className="w-full p-4 border border-border bg-background text-foreground outline-none transition-colors focus:border-foreground placeholder:text-muted-foreground"
                />
              </div>
            </div>
          )}
        </div>

        <div className="space-y-6">
          <div className="bg-card border border-border p-6 h-full">
            <h3 className="text-foreground mb-4 flex items-center gap-2" style={{ fontSize: '1.05rem', fontWeight: 500 }}>
              <FileText className="w-5 h-5 text-muted-foreground" />
              Caption &amp; tags
            </h3>
            <div className="space-y-4">
              <textarea
                value={script.caption}
                onChange={(e) => setScript({ ...script, caption: e.target.value })}
                placeholder="Write your caption here (optional)…"
                className="w-full p-4 border border-border bg-background text-foreground outline-none transition-colors focus:border-foreground min-h-[200px] placeholder:text-muted-foreground"
              />
              <div className="flex items-center gap-2 bg-background p-3 border border-border">
                <Hash className="w-4 h-4 text-muted-foreground" />
                <input
                  type="text"
                  value={script.hashtags}
                  onChange={(e) => setScript({ ...script, hashtags: e.target.value })}
                  placeholder="Add tags…"
                  className="flex-1 outline-none bg-transparent text-foreground placeholder:text-muted-foreground"
                />
              </div>
            </div>
            <div className="mt-8 pt-6 border-t border-border space-y-3">
              <button
                onClick={() => handleSave(true)}
                disabled={loading}
                className="btn-ie btn-ie-solid w-full disabled:opacity-40 disabled:cursor-not-allowed"
              >
                <span className="btn-ie-text flex items-center gap-2">
                  Save &amp; continue <ChevronRight className="w-4 h-4" />
                </span>
              </button>
              <button
                onClick={onSkip}
                className="w-full py-2 t-micro text-muted-foreground hover:text-foreground transition-colors"
              >
                Skip scripting
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
